const extern inline register 
restrict static volatile auto 
char double enum float 
int long short signed 
struct union unsigned void 
break case continue default 
do else for goto 
if return sizeof switch 
typedef while getchar printf 
putchar scanf ! != 
& && &= * 
*= + ++ += 
- -- -= . 
/ /= : < 
<< <<= <= = 
== > >= >> 
>>= ? ^ ^= 
| |= || ~ 
, ; ( ) 
[ ] { } 