const extern inline register 
static volatile char double 
float int long short 
signed struct union unsigned 
void; break case continue 
default do else for 
goto if return sizeof 
switch while getchar printf 
putchar scanf ! != 
& && &= * 
*= + ++ += 
- -- -= . 
/ /= : < 
<< <<= <= = 
== > >= >> 
>>= ? ^ ^= 
| |= || ~ 
,   ( ) 
[ ] { }